### ISSUE TITLE
Magstripe causes program to hang/pause

### ISSUE THREAD

**Issue by PrattTechnologies** [carlosefr/magstripelib#5]
I am using the MagStrip library (https://github.com/carlosefr/magstripelib 1). In my main loop I call the function which runs the code:

```
void magcardFunc()
{
static const byte DATA_BUFFER_LEN = 108;
static char magcard[DATA_BUFFER_LEN];
  
// Don't do anything if there isn't a card present

  if (!card.available()) {
    return;
  }

    // Read the card into the buffer "magcard" (as a null-terminated string)
  short chars = card.read(magcard, DATA_BUFFER_LEN);

  if (chars < 0) {
    Serial.print("bad read");
    return;
  }
  
  // Send the data to the computer if data was read
  if (chars != 0) {
    Serial.print(magcardstr);
  }
}
```
The code successfully reads a magnetic card when inserted.

The problem is, I have other functions which are called from the main loop but they do not get called as the code pauses at:

```
if (!card.available()) {
    return;
  }

    // Read the card into the buffer "magcard" (as a null-terminated string)
  short chars = card.read(magcard, DATA_BUFFER_LEN);
```
If I insert a card into my mag reader (and leave it there), the program continues and the other functions are called. I want the main loop to continue and the other functions be called without having to leave a card inserted.

I have tried removing the IF statement:

```
if (!card.available()) {
    return;
  }
```
and I have tried reversing it

```
if (card.available()) {
    return;
  }
```
If I reverse it as above, the other functions run but when I do swipe a card, it is not read.
I get no compiler errors.

An example sketch:

```
#include <MagStripe.h>

void magcardFunc();
void otherFunc();

MagStripe card;

static const byte DATA_BUFFER_LEN = 108;
static char data[DATA_BUFFER_LEN];


void setup()
{
  // The card data will be sent over serial...
  Serial.begin(9600);
  
  // Initialize the library for reading track 2...
  card.begin(2);
}


void loop()
{
  magcardFunc();
  otherFunc();
}
 
void magcardFunc()
{
  // Don't do anything if there isn't a card present...
  if (!card.available()) {
    return;
  }
  
  
  // Read the card into the buffer "data" (as a null-terminated string)...
  short chars = card.read(data, DATA_BUFFER_LEN);
  

  if (chars < 0) {
  Serial.println("no chars");

    return;
  }

  // Send the data to the computer...
  Serial.println(data);
}

void otherFunc()
{
  Serial.println("I am another function");
  delay(500); //feel free to remove me
}
```

Any help is appreciated.

**Comment by carlosefr** [comment]
All the `available()` method [does](https://github.com/carlosefr/magstripelib/blob/master/MagStripe.cpp#L79) is return `true` when the CLS pin is low. Now, when you call the `read()` method it will [block](https://github.com/carlosefr/magstripelib/blob/master/MagStripe.cpp#L95) until CLS goes high. The actual data is read asynchronously by the interrupt handlers attached to the data and clock pins.

To remove this blocking behavior you will have to change the library itself and break `read()` into two separate calls: one to reset the buffer when CLS goes low and another to decode the data when CLS goes high. In between the two you can run your own code.

Another (perhaps better) way is to have `read()` return nothing if the buffer is empty or a card is still being read.
