### ISSUE TITLE
ISR not in IRAM! User exception (panic/abort/assert)

### ISSUE THREAD

**Issue by braysonjohn148** [carlosefr/magstripelib#6]
Am using NodeMCU 1.0 ESP8266

At startup it bring this error.

ctx: cont
sp: 3ffffee0 end: 3fffffc0 offset: 0000
3ffffee0:  00000688 feefeffe feefeffe feefeffe  
3ffffef0:  000000fe 00000000 00000000 00000000  
3fffff00:  00000000 00000000 00000000 00ff0000  
3fffff10:  5ffffe00 5ffffe00 feefeffe 00000000  
3fffff20:  00000003 00000000 3ffee354 402021ba  
3fffff30:  40100462 00002580 00000000 402021d0  
3fffff40:  00000003 40203199 3ffee354 402026e1  
3fffff50:  00000000 00000001 3ffee3e0 3ffee448  
3fffff60:  00000000 00000001 3ffee3e0 3ffee448  
3fffff70:  3fffdad0 00000000 3ffee354 40202790  
3fffff80:  00002580 0000001c 00000000 40201228  
3fffff90:  3fffdad0 00000000 3ffee408 40201050  
3fffffa0:  feefeffe feefeffe feefeffe 40201e10  
3fffffb0:  feefeffe feefeffe 3ffe84e4 40100d6d  
<<<stack<<<
H!⸮ԅ⸮⸮⸮⸮⸮ISR not in IRAM!

User exception (panic/abort/assert)
Abort called

**Comment by carlosefr** [comment]
According to [this](https://www.malabdali.com/arduino-and-esp32-interrupts/), you may need to add `IRAM_ATTR` to both interrupt handlers in https://github.com/carlosefr/magstripelib/blob/master/MagStripe.cpp#L264-L279. I never tested this library with NodeMCU, additional changes may be needed.

**Comment by braysonjohn148** [comment]
Installed succesfully on ESP32, i can't seem to get it work. I don't know it is my connection... My MagStripe reader came with 11 pins(black,red,brown,orange,white,yellow,green,blue,purple,grey,white) respectively. It is written it uses TTL protocol, with my little understanding in electronics I connected reader's green,blue to GPIO1,GPIO3 of the esp32.

**Comment by carlosefr** [comment]
11 pins could mean one set of 3 pins for each of the 3 tracks (data, clock, card present) plus power and ground. It sounds weird to have one card present pin per track, but I guess it could be used to signal the presence of each track. The device's datasheet (if it exists) should tell you if that's the case.

But, like I said before, this library was never tested on anything besides an Arduino Uno board and may not work with an ESP without further changes.

**Comment by braysonjohn148** [comment]
Am new to Arduino programming, is there a way we could get it to work in these few days? I have this project has to get working in a few days and this library is the only one existing with Magnetic stripe readers.

[https://www.aliexpress.com/item/32797329185.html?spm=a2g0o.order_list.0.0.65301802WuIGLJ](url)

**Comment by carlosefr** [comment]
I'm not actively maintaining this library anymore, but knowing if it works with that reader and an ESP32 is something that requires you first identify the pinout of the reader. The reader itself likely has some model number or other piece of information (outside or inside) you can use to google for a datasheet.
